name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  screenshot: ^2.1.0
  geolocator: ^11.0.0
  geocoding: ^2.2.2
  http: ^1.2.2
  mongo_dart: ^0.10.1
  provider: ^6.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  location: ^7.0.1
  permission_handler: ^10.4.3
  google_maps_flutter: ^2.10.1
  geolocator_android: 4.6.1
  font_awesome_flutter: ^10.1.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/worker.jpg
    - assets/money.png
    - assets/trackter.png
    - assets/kid.png
    - assets/human.png
    - assets/human1.png
    - assets/พืชผัก.jpg
    - assets/พืชไร่.jpg
    - assets/ผลไม้.jpg
    - assets/พืชสวน.jpg
    - assets/น้ำบาดาล.png
    - assets/ขุดสระ.png
    - assets/น้ำชลประทาน.png
    - assets/ธรรมชาติ.png
    - assets/ดินทราย.png
    - assets/ดินเหนียว.png
    - assets/ดินร่วน.png
    - assets/logo.png
    - assets/โปรไฟล์.png
    - assets/โฮม.png
    - assets/ข้อมูลแปลง.png
    - assets/ประวัติ.png
    - assets/แนะนำ.png

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700
